# Generated by Django 6.0.1 on 2026-05-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('servings', models.IntegerField(default=2)),
                ('reference_url', models.URLField(blank=True)),
                ('memo', models.TextField(blank=True)),
            ],
        ),
    ]
