# Generated by Django 6.0.1 on 2026-06-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_integer_only',
            field=models.BooleanField(default=False),
        ),
    ]
